<?php
define('APP_ENV',               isset($_SERVER['APP_ENV']) ? $_SERVER['APP_ENV'] : 'development');

define('APP_ROOT',              realpath(dirname(__FILE__) . '/../..'));
define('OFFSITE_ROOT',          APP_ROOT . '/_offsite');
define('ENVIRONMENT_ROOT',      OFFSITE_ROOT . '/environment');
define('INCLUDE_ROOT',          OFFSITE_ROOT . '/include');
define('LIB_ROOT',              INCLUDE_ROOT . '/lib');

set_include_path('.:' . LIB_ROOT);

env('main');

//
// Core functions

function env($file) {
    require ENVIRONMENT_ROOT . '/' . APP_ENV . '/' . $file . '.php';
}

//
// Setup globals and dependencies

$TPL = new Template;

//
// Autoloader gubbins; this is mostly autogenerated, see the Rakefile for details

function class_map_autoloader($class) {

    // START-MAP
    static $map = array (
      'Annotation' => 'base/Annotation.php',
      'Arrays' => 'base/Arrays.php',
      'Base' => 'base/Base.php',
      'Callback' => 'base/Callback.php',
      'FunctionCallback' => 'base/Callback.php',
      'InstanceCallback' => 'base/Callback.php',
      'StaticCallback' => 'base/Callback.php',
      'Component' => 'base/Component.php',
      'Event' => 'base/Component.php',
      'Component_Extension' => 'base/Component.php',
      'Date' => 'base/Date.php',
      'Errors' => 'base/Errors.php',
      'File' => 'base/File.php',
      'GDB_Exception' => 'base/GDB.php',
      'GDB_RollbackException' => 'base/GDB.php',
      'GDB_QueryException' => 'base/GDB.php',
      'GDB_IntegrityConstraintViolation' => 'base/GDB.php',
      'GDB_ForeignKeyViolation' => 'base/GDB.php',
      'GDB_UniqueViolation' => 'base/GDB.php',
      'GDB_CheckViolation' => 'base/GDB.php',
      'GDB' => 'base/GDB.php',
      'GDBMySQL' => 'base/GDB.php',
      'GDBResult' => 'base/GDB.php',
      'GDBResultMySQL' => 'base/GDB.php',
      'H' => 'base/H.php',
      'H_Table' => 'base/H.php',
      'Error_UnsupportedImageType' => 'base/Image.php',
      'Image' => 'base/Image.php',
      'Inflector' => 'base/Inflector.php',
      'Validatable' => 'base/Interfaces.php',
      'MIME' => 'base/MIME.php',
      'Money_ConversionError' => 'base/Money.php',
      'Money' => 'base/Money.php',
      'Money_Bank' => 'base/Money.php',
      'HTTP_Request' => 'base/Request.php',
      'Template' => 'base/Template.php',
      'V' => 'base/V.php',
      'XML_RPC' => 'base/XML/RPC.php',
      'XML_RPC_Request' => 'base/XML/RPC.php',
      'XML_RPC_Response' => 'base/XML/RPC.php',
      'Error_AssertionFailed' => 'base/Test/Base.php',
      'Test_Base' => 'base/Test/Base.php',
      'Test_ConsoleReporter' => 'base/Test/ConsoleReporter.php',
      'Test_Invoker' => 'base/Test/Invoker.php',
      'Test_MethodInvoker' => 'base/Test/MethodInvoker.php',
      'Test_Reporter' => 'base/Test/Reporter.php',
      'Test_Suite' => 'base/Test/Suite.php',
      'Test_Unit' => 'base/Test/Unit.php',
      'Model_StateError' => 'base/Model/Base.php',
      'Model_NoSuchAttributeError' => 'base/Model/Base.php',
      'Model_Base' => 'base/Model/Base.php',
      'Model_Association' => 'base/Model/Base.php',
      'Model_Association_HasOne' => 'base/Model/Base.php',
      'Model_Association_HasMany' => 'base/Model/Base.php',
      'Model_Association_BelongsTo' => 'base/Model/Base.php',
      'ISO_Country' => 'base/ISO/Country.php',
      'ISO_Language' => 'base/ISO/Language.php',
      'GDB_SQL' => 'base/GDB/SQL.php',
      'File_Upload' => 'base/File/Upload.php',
      'Error_IllegalArgument' => 'base/Error/IllegalArgument.php',
      'Error_IllegalState' => 'base/Error/IllegalState.php',
      'Error_IO' => 'base/Error/IO.php',
      'Error_MethodMissing' => 'base/Error/MethodMissing.php',
      'Error_NoSuchElement' => 'base/Error/NoSuchElement.php',
      'Error_NotFound' => 'base/Error/NotFound.php',
      'Error_OutOfBounds' => 'base/Error/OutOfBounds.php',
      'Error_Syntax' => 'base/Error/Syntax.php',
      'Error_UnsupportedOperation' => 'base/Error/UnsupportedOperation.php',
      'Date_Interval' => 'base/Date/Interval.php',
      'Date_Range' => 'base/Date/Range.php',
      'Date_Time' => 'base/Date/Time.php',
      'Contact_Form' => 'base/Contact/Form.php',
      'Contact_Form_Field' => 'base/Contact/Form.php',
      'Contact_Form_Text' => 'base/Contact/Form.php',
      'Contact_Form_Textarea' => 'base/Contact/Form.php',
      'Contact_Form_Select' => 'base/Contact/Form.php',
      'Contact_Form_Date' => 'base/Contact/Form.php',
      'Contact_Form_Time' => 'base/Contact/Form.php',
      'Contact_Form_Checkbox' => 'base/Contact/Form.php',
      'Contact_Form_File' => 'base/Contact/Form.php',
      'Contact_Mailer' => 'base/Contact/Form.php',
      'Contact_CSV' => 'base/Contact/Form.php',
    );
    // END-MAP

    if (isset($map[$class])) require $map[$class];

}

spl_autoload_register('class_map_autoloader');
?>